import { useCallback, useEffect, useState } from "react";
import PageHeader from "../../components/ui/PageHeader";
import DataTable, { Column } from "../../components/tables/DataTable";
import Card from "../../components/common/Card";
import StatusBadge from "../../components/ui/StatusBadge";
import CurrencyDisplay from "../../components/ui/CurrencyDisplay";
import { formatDate } from "../../utils/date";
import { getErrorMessage } from "../../utils/errors";
import { SubscriptionPayment } from "../../types/models";
import { listSubscriptionPayments } from "../../services/subscriptionPayment.service";

export default function SubscriptionPaymentsListPage() {
  const [rows, setRows] = useState<SubscriptionPayment[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await listSubscriptionPayments();
      setRows(res.subscriptionPayments);
    } catch (err) {
      setError(getErrorMessage(err, "Couldn't load subscription payments."));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const columns: Column<SubscriptionPayment>[] = [
    { header: "Billing period", accessor: (p) => p.billing_period },
    { header: "Amount", accessor: (p) => <CurrencyDisplay value={p.amount} currency={p.currency} /> },
    { header: "Status", accessor: (p) => <StatusBadge status={p.status} /> },
    { header: "Due date", accessor: (p) => formatDate(p.due_date) },
    { header: "Paid at", accessor: (p) => formatDate(p.paid_at) },
  ];

  return (
    <div>
      <PageHeader title="Subscription Payments" description="Billing cycles generated by active subscriptions." />
      <Card className="!p-0">
        <DataTable columns={columns} rows={rows} rowKey={(p) => p.id} loading={loading} error={error} onRetry={load} emptyTitle="No subscription payments yet" />
      </Card>
    </div>
  );
}
