import { prisma } from "../../config/database.js";
import { callOpenRouter } from "../../config/ai.js";

type CommunicationChannel =
    | "EMAIL"
    | "SMS"
    | "WHATSAPP";

type CommunicationResult = {
    channel: CommunicationChannel;
    subject: string;
    message: string;
    reason: string;
    confidence: "LOW" | "MEDIUM" | "HIGH";
};

export async function generateCustomerCommunication(
    userId: string,
    recoveryCaseId: string
) {
    // --------------------------------------------------
    // 1. Get merchant from authenticated profile
    // --------------------------------------------------

    const profile = await prisma.profiles.findUnique({
        where: {
            id: userId,
        },
        select: {
            merchant_id: true,
        },
    });

    if (!profile) {
        throw new Error("Merchant profile not found");
    }

    if (!profile.merchant_id) {
        throw new Error("Merchant is not associated with profile");
    }

    // --------------------------------------------------
    // 2. Get recovery case
    // --------------------------------------------------

    const recoveryCase =
        await prisma.recovery_cases.findFirst({
            where: {
                id: recoveryCaseId,
                merchant_id: profile.merchant_id,
            },
            include: {
                customers: true,
                payments: true,
                recovery_actions: true,
            },
        });

    if (!recoveryCase) {
        throw new Error("Recovery case not found");
    }

    if (!recoveryCase.customers) {
        throw new Error(
            "Recovery case has no customer information"
        );
    }

    // --------------------------------------------------
    // 3. Get latest AI prediction
    // --------------------------------------------------

    const prediction =
        await prisma.ai_predictions.findFirst({
            where: {
                recovery_case_id: recoveryCaseId,
                merchant_id: profile.merchant_id,
            },
            orderBy: {
                created_at: "desc",
            },
        });

    // Prediction is useful but communication can still
    // work without one.
    const predictionData = prediction
        ? {
              recoveryScore:
                  prediction.recovery_score,
              recoveryProbability:
                  prediction.recovery_probability,
              expectedRecoveryAmount:
                  prediction.expected_recovery_amount,
              confidence: prediction.confidence,
              reasons:
                  prediction.prediction_reasons,
          }
        : null;

    // --------------------------------------------------
    // 4. Get latest AI decision
    // --------------------------------------------------

    const decision =
        await prisma.ai_decisions.findFirst({
            where: {
                recovery_case_id: recoveryCaseId,
                merchant_id: profile.merchant_id,
            },
            orderBy: {
                created_at: "desc",
            },
        });

    const decisionData = decision
        ? {
              recommendedAction:
                  decision.recommended_action,
              reasoning:
                  decision.reasoning_summary,
              confidence: decision.confidence,
              structuredDecision:
                  decision.structured_decision,
          }
        : null;

    // --------------------------------------------------
    // 5. Build AI prompt
    // --------------------------------------------------

    const prompt = `
You are the Customer Communication Agent
for an AI payment recovery platform.

Your job is to create a personalized message
for a customer whose payment failed.

Use the recovery case, customer information,
payment information, AI prediction, and AI decision.

Choose exactly ONE communication channel:

EMAIL
SMS
WHATSAPP

Return ONLY valid JSON in exactly this format:

{
    "channel": "EMAIL | SMS | WHATSAPP",
    "subject": "string",
    "message": "string",
    "reason": "string",
    "confidence": "LOW | MEDIUM | HIGH"
}

Rules:

1. Do not expose internal AI information.
2. Do not mention recovery scores.
3. Do not mention internal database IDs.
4. Do not mention that the message was generated by AI.
5. Be polite and concise.
6. Do not threaten the customer.
7. Do not invent payment details.
8. If the customer needs to update their payment method,
   clearly explain that.
9. If another retry is scheduled, tell the customer
   that another attempt will be made.
10. For SMS and WHATSAPP keep the message short.
11. For EMAIL provide a useful subject.
12. The message should be appropriate for a real
    payment recovery product.

Recovery Case:
${JSON.stringify({
    id: recoveryCase.id,
    originalAmount:
        Number(recoveryCase.original_amount),
    recoverableAmount:
        Number(recoveryCase.recoverable_amount),
    recoveredAmount:
        Number(recoveryCase.recovered_amount),
    status: recoveryCase.status,
    priority: recoveryCase.priority,
})}

Customer:
${JSON.stringify({
    name: recoveryCase.customers?.name,
    email: recoveryCase.customers?.email,
    phone: recoveryCase.customers?.phone,
    country: recoveryCase.customers?.country,
})}

Payment:
${JSON.stringify({
    amount: Number(
        recoveryCase.payments?.amount ?? 0
    ),
    currency:
        recoveryCase.payments?.currency,
    status:
        recoveryCase.payments?.status,
    failureCode:
        recoveryCase.payments?.failure_code,
    failureMessage:
        recoveryCase.payments?.failure_message,
})}

AI Prediction:
${JSON.stringify(predictionData)}

AI Decision:
${JSON.stringify(decisionData)}

Previous Recovery Actions:
${JSON.stringify(
    recoveryCase.recovery_actions.map(
        (action) => ({
            actionType:
                action.action_type,
            status:
                action.status,
            attemptNumber:
                action.attempt_number,
            scheduledAt:
                action.scheduled_at,
        })
    )
)}
`;

    // --------------------------------------------------
    // 6. Call OpenRouter
    // --------------------------------------------------

    const aiResponse = await callOpenRouter([
        {
            role: "system",
            content:
                "You are a professional customer payment communication agent. Return ONLY valid JSON.",
        },
        {
            role: "user",
            content: prompt,
        },
    ]);

    // --------------------------------------------------
    // 7. Parse AI response
    // --------------------------------------------------

    let communication: CommunicationResult;

    try {
        communication =
            typeof aiResponse === "string"
                ? JSON.parse(aiResponse)
                : aiResponse;
    } catch {
        throw new Error(
            "AI returned invalid communication JSON"
        );
    }

    // --------------------------------------------------
    // 8. Validate response
    // --------------------------------------------------

    const validChannels: CommunicationChannel[] = [
        "EMAIL",
        "SMS",
        "WHATSAPP",
    ];

    if (
        !validChannels.includes(
            communication.channel
        )
    ) {
        throw new Error(
            "AI returned an invalid communication channel"
        );
    }

    if (
        typeof communication.subject !==
        "string"
    ) {
        throw new Error(
            "AI returned an invalid communication subject"
        );
    }

    if (
        typeof communication.message !==
        "string"
    ) {
        throw new Error(
            "AI returned an invalid communication message"
        );
    }

    if (
        typeof communication.reason !==
        "string"
    ) {
        throw new Error(
            "AI returned an invalid communication reason"
        );
    }

    if (
        !["LOW", "MEDIUM", "HIGH"].includes(
            communication.confidence
        )
    ) {
        throw new Error(
            "AI returned an invalid communication confidence"
        );
    }

    // --------------------------------------------------
    // 9. Save AI decision
    // --------------------------------------------------
    //
    // IMPORTANT:
    // recommended_action MUST be strategy_type.
    //
    // EMAIL/SMS/WHATSAPP are notification channels,
    // NOT strategy types.
    //
    // Therefore:
    // recommended_action = CUSTOMER_REMINDER
    //
    // The actual channel is stored inside
    // structured_decision.
    // --------------------------------------------------

    const savedCommunication =
        await prisma.ai_decisions.create({
            data: {
                merchant_id:
                    profile.merchant_id,

                recovery_case_id:
                    recoveryCase.id,

                prediction_id:
                    prediction?.id ?? null,

                agent_name:
                    "customer_communication_agent",

                decision_type:
                    "CUSTOMER_COMMUNICATION",

                recommended_action:
                    "CUSTOMER_REMINDER",

                reasoning_summary:
                    communication.reason,

                confidence:
                    communication.confidence,

                structured_decision: {
                    channel:
                        communication.channel,

                    subject:
                        communication.subject,

                    message:
                        communication.message,

                    reason:
                        communication.reason,

                    confidence:
                        communication.confidence,
                },
            },
        });

    // --------------------------------------------------
    // 10. Return result
    // --------------------------------------------------

    return {
        communication,
        aiDecision: savedCommunication,
    };
}